per_page: 15
pages:
  per_user: 10
pages:
  per: 10
course_times: 2
task_times: 2
default_image: "/assets/training.png"
format_time: "%d/%m/%Y"
batch_job:
  assign_to_course: 1
  remove_from_course: 2
  mail_from: "trananh9a@gmail.com"
